<<<<<<< HEAD
export 'specialty.dart';
export 'clinic_info.dart';
export 'patient.dart';
=======
export 'api_response.dart';
export 'appointment.dart';
export 'available_schedule.dart';
export 'clinic.dart';
export 'clinic_info.dart';
export 'doctor.dart';
export 'doctor_clinic.dart';
export 'doctor_clinic_pivot.dart';
export 'doctor_work_pattern.dart';
export 'enum_days.dart';
export 'patient.dart';
export 'specialty.dart';
export 'user.dart';
>>>>>>> 351c467fab9745fcbe292ed394ca0ff98ba10f5b
